# Generated by Django 4.2.11 on 2026-05-05 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('occupancy', 'Загрузка помещений'), ('revenue', 'Доходы'), ('clients', 'Клиенты'), ('bookings', 'Бронирования')], max_length=20, verbose_name='Тип отчета')),
                ('format', models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV'), ('pdf', 'PDF')], default='json', max_length=10, verbose_name='Формат')),
                ('parameters', models.JSONField(default=dict, verbose_name='Параметры')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/%d/', verbose_name='Файл')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('processing', 'Генерация'), ('completed', 'Готов'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('admin', models.ForeignKey(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Администратор')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
                'ordering': ['-created_at'],
            },
        ),
    ]
