# Generated by Django 4.2.11 on 2026-05-05 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
        ('tariffs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Индивидуальная цена')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_tariffs', to='spaces.place', verbose_name='Место')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_tariffs', to='tariffs.tariff', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Тариф места',
                'verbose_name_plural': 'Тарифы мест',
                'unique_together': {('place', 'tariff')},
            },
        ),
    ]
