# Generated by Django 4.2.11 on 2026-05-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0002_placetariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='placetariff',
            name='version',
            field=models.IntegerField(default=0, editable=False, verbose_name='Версия'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='version',
            field=models.IntegerField(default=0, editable=False, verbose_name='Версия'),
        ),
    ]
