# Generated by Django 4.2.11 on 2026-05-05 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tariffs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_type', models.CharField(choices=[('desk', 'Рабочее место'), ('meeting_room', 'Переговорная')], db_column='type', max_length=20, verbose_name='Тип')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('capacity', models.PositiveIntegerField(default=1, verbose_name='Вместимость')),
                ('x', models.IntegerField(blank=True, help_text='Координата X на схеме', null=True, verbose_name='Координата X')),
                ('y', models.IntegerField(blank=True, help_text='Координата Y на схеме', null=True, verbose_name='Координата Y')),
                ('characteristics', models.JSONField(blank=True, default=dict, verbose_name='Характеристики')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='places/preview/', verbose_name='Превью (150x150)')),
                ('gallery_images', models.JSONField(blank=True, default=list, verbose_name='Галерея фото (массив URL)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('base_tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places_base', to='tariffs.tariff', verbose_name='Базовый тариф')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
                'ordering': ['space', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('total_places', models.PositiveIntegerField(default=0, verbose_name='Всего мест')),
                ('image', models.ImageField(blank=True, null=True, upload_to='spaces/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Помещение',
                'verbose_name_plural': 'Помещения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlacePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='places/gallery/', verbose_name='Фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='spaces.place', verbose_name='Место')),
            ],
            options={
                'verbose_name': 'Фото места',
                'verbose_name_plural': 'Фото мест',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='place',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='spaces.space', verbose_name='Помещение'),
        ),
    ]
