# Generated by Django 4.2.11 on 2026-05-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='map_image',
            field=models.ImageField(blank=True, null=True, upload_to='spaces/maps/', verbose_name='План помещения'),
        ),
    ]
