# Generated by Django 4.2.11 on 2026-05-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_booking_duration', models.PositiveIntegerField(default=30, verbose_name='Минимальная длительность бронирования (минуты)')),
                ('max_booking_duration', models.PositiveIntegerField(default=1440, verbose_name='Максимальная длительность бронирования (минуты)')),
                ('booking_interval', models.PositiveIntegerField(default=15, verbose_name='Интервал бронирования (минуты)')),
                ('advance_booking_days', models.PositiveIntegerField(default=30, verbose_name='Максимальный срок бронирования (дни)')),
                ('cancellation_deadline_minutes', models.PositiveIntegerField(default=120, verbose_name='Время для отмены бронирования (минуты)')),
                ('allow_simultaneous_bookings', models.BooleanField(default=False, verbose_name='Разрешить одновременные бронирования')),
                ('max_simultaneous_bookings', models.PositiveIntegerField(default=1, verbose_name='Максимум одновременных бронирований')),
                ('auto_cancel_unpaid_minutes', models.PositiveIntegerField(default=30, verbose_name='Автоотмена неоплаченных бронирований (минуты)')),
                ('enable_notifications', models.BooleanField(default=True, verbose_name='Включить уведомления')),
                ('reminder_minutes_before', models.PositiveIntegerField(default=60, verbose_name='Напоминание за (минуты)')),
            ],
            options={
                'verbose_name': 'Настройки бронирования',
                'verbose_name_plural': 'Настройки бронирования',
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], unique=True, verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Начало работы')),
                ('end_time', models.TimeField(verbose_name='Окончание работы')),
                ('is_working', models.BooleanField(default=True, verbose_name='Рабочий день')),
            ],
            options={
                'verbose_name': 'Рабочие часы',
                'verbose_name_plural': 'Рабочие часы',
                'ordering': ['day'],
            },
        ),
    ]
