# Generated by Django 4.2.11 on 2026-05-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsettings',
            name='version',
            field=models.IntegerField(default=0, editable=False, verbose_name='Версия'),
        ),
        migrations.AddField(
            model_name='workinghours',
            name='version',
            field=models.IntegerField(default=0, editable=False, verbose_name='Версия'),
        ),
    ]
