# Generated by Django 4.2.11 on 2026-05-05 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=50, unique=True, verbose_name='Номер карты')),
                ('pin_code', models.CharField(blank=True, max_length=10, verbose_name='PIN-код')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выдачи')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Срок действия')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее использование')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_card', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пропуск',
                'verbose_name_plural': 'Пропуски',
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('entry', 'Вход'), ('exit', 'Выход'), ('denied', 'Отказ')], max_length=10, verbose_name='Событие')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('door', models.CharField(blank=True, max_length=50, verbose_name='Дверь')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Причина')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='access.accesscard', verbose_name='Пропуск')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог доступа',
                'verbose_name_plural': 'Логи доступа',
                'ordering': ['-timestamp'],
            },
        ),
    ]
