# Generated by Django 4.2.11 on 2026-05-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='ID транзакции'),
        ),
    ]
